# Syncs all Github Forks with Ander's main branch: https://github.com/AnderUstarroz/cubist-games-frontend
name: Sync Forks

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: AnderUstarroz
          base: main
          head: main
